=== hmrc/api-platform-test-user/resources/public/api/conf/1.0/schemas/create-organisation-response.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Create Organisation Response",
  "type": "object",
  "properties": {
    "userId": {
      "type": "string",
      "description": "Government Gateway ID."
    },
    "password": {
      "type": "string",
      "description": "Government Gateway password."
    },
    "userFullName": {
      "type": "string",
      "description": "Government Gateway user's full name."
    },
    "emailAddress": {
      "type": "string",
      "description": "Government Gateway user's email address."
    },
    "organisationDetails": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "Organisation name."
        },
        "address": {
          "type": "object",
          "properties": {
            "line1": {
              "type": "string",
              "description": "Organisation's first line of address."
            },
            "line2": {
              "type": "string",
              "description": "Organisation's second line of address."
            },
            "postcode": {
              "type": "string",
              "description": "Organisation's postcode."
            }
          },
          "required": [
            "line1",
            "line2",
            "postcode"
          ]
        }
      },
      "required": [
        "name",
        "address"
      ]
    },
    "individualDetails": {
      "type": "object",
      "properties": {
        "firstName": {
          "type": "string",
          "description": "Individual's first name."
        },
        "lastName": {
          "type": "string",
          "description": "Individual's last name."
        },
        "dateOfBirth": {
          "type": "string",
          "format": "date",
          "description": "Individual's date of birth."
        },
        "address": {
          "type": "object",
          "properties": {
            "line1": {
              "type": "string",
              "description": "Individual's first line of address."
            },
            "line2": {
              "type": "string",
              "description": "Individual's second line of address."
            },
            "postcode": {
              "type": "string",
              "description": "Individual's postcode."
            }
          },
          "required": [
            "line1",
            "line2",
            "postcode"
          ]
        }
      },
      "required": [
        "firstName",
        "lastName",
        "dateOfBirth",
        "address"
      ]
    },
    "saUtr": {
      "type": "string",
      "description": "Self Assessment UTR."
    },
    "nino": {
      "type": "string",
      "description": "National Insurance number."
    },
    "mtdItId": {
      "type": "string",
      "description": "Making Tax Digital Income Tax ID."
    },
    "empRef": {
      "type": "string",
      "description": "Employer Reference."
    },
    "ctUtr": {
      "type": "string",
      "description": "Corporation Tax UTR."
    },
    "vrn": {
      "type": "string",
      "description": "VAT Reference Number."
    },
    "vatRegistrationDate": {
      "type": "string",
      "format": "date",
      "description": "Date of registration for VAT."
    },
    "lisaManagerReferenceNumber": {
      "type": "string",
      "description": "LISA Manager Reference Number, in either 4-digit format (Znnnn) or 6-digit format (Znnnnnn)."
    },
    "secureElectronicTransferReferenceNumber": {
      "type": "string",
      "description": "Secure Electronic Transfer reference number."
    },
    "pensionSchemeAdministratorIdentifier": {
      "type": "string",
      "description": "Pension Scheme Administrator Identifier."
    },
    "eoriNumber": {
      "type": "string",
      "description": "Economic Operator Registration and Identification (EORI) number."
    },
    "exciseNumber": {
      "type": "string",
      "description": "Excise Number."
    },
    "crn": {
      "type": "string",
      "description": "Company Reference Number"
    },
    "taxPayerType": {
      "type": "string",
      "description": "Type of Self Assessment taxpayer One of 'Individual' or 'Partnership'"
    },
    "pillar2Id": {
      "type": "string",
      "description": "Pillar 2 ID"
    },
    "zReference": {
      "type": "string",
      "description": "ISA Manager Z Reference, in 4-digit format (Znnnn)."
    },
    "capitalGainsTaxOnUKPropertyReference": {
      "type": "string",
      "description": "Capital Gains Tax on UK Property reference."
    },
    "plasticPackagingTaxRegistrationNumber": {
      "type": "string",
      "description": "Plastic Packaging Tax registration number."
    },
    "countryByCountryReportingId": {
      "type": "string",
      "description": "Country-by-Country Reporting ID."
    },
    "trustsUniqueTaxpayerReference": {
      "type": "string",
      "description": "Unique Taxpayer Reference for a taxable trust."
    },
    "trustsUniqueReferenceNumber": {
      "type": "string",
      "description": "Unique Reference Number for a non-taxable trust."
    }
  },
  "required": [
    "userId",
    "password",
    "userFullName",
    "emailAddress",
    "organisationDetails"
  ]
}

=== hmrc/api-platform-test-user/resources/public/api/conf/1.0/examples/create-organisation-response.json
{
  "userId":"085603622877",
  "password":"nyezgdfrlsmc",
  "userFullName": "Ida Newton",
  "emailAddress": "ida.newton@example.com",
  "organisationDetails": {
    "name":"Company ABF123",
    "address": {
      "line1":"1 Abbey Road",
      "line2":"Aberdeen",
      "postcode": "TS1 1PA"
    }
  },
  "individualDetails": {
    "firstName": "Ida",
    "lastName": "Newton",
    "dateOfBirth": "1960-06-01",
    "address": {
      "line1": "45 Springfield Rise",
      "line2": "Glasgow",
      "postcode": "TS1 1PA"
    }
  },
  "saUtr":"8000083480",
  "nino":"XM110477D",
  "empRef":"538/EMKXYNSVTH",
  "ctUtr":"4000082459",
  "vrn":"666119668",
  "vatRegistrationDate":"2001-11-02",
  "mtdItId":"XJIT00000328268",
  "lisaManagerReferenceNumber":"Z123456",
  "secureElectronicTransferReferenceNumber":"123456789012",
  "pensionSchemeAdministratorIdentifier":"A1234567",
  "eoriNumber":"GB123456789012",
  "exciseNumber":"GBWK254706100",
  "crn": "12345678",
  "taxPayerType":"Individual",
  "pillar2Id":"XA1234567890123",
  "zReference": "Z1234",
  "capitalGainsTaxOnUKPropertyReference": "XACGTP123456789",
  "plasticPackagingTaxRegistrationNumber": "XAPPT0001234567",
  "countryByCountryReportingId": "XACBC1234567890",
  "trustsUniqueTaxpayerReference": "8876543210",
  "trustsUniqueReferenceNumber": "XATRUST12345678"
}
