=== hmrc/api-platform-test-user/resources/public/api/conf/1.0/schemas/create-individual-response.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Create Individual Response",
  "type": "object",
  "properties": {
    "userId": {
      "type": "string",
      "description": "Government Gateway ID."
    },
    "password": {
      "type": "string",
      "description": "Government Gateway password."
    },
    "userFullName": {
      "type": "string",
      "description": "Government Gateway user's full name."
    },
    "emailAddress": {
      "type": "string",
      "description": "Government Gateway user's email address."
    },
    "individualDetails": {
      "type": "object",
      "properties": {
        "firstName": {
          "type": "string",
          "description": "Individual's first name."
        },
        "lastName": {
          "type": "string",
          "description": "Individual's last name."
        },
        "dateOfBirth": {
          "type": "string",
          "format": "date",
          "description": "Individual's date of birth."
        },
        "address": {
          "type": "object",
          "properties": {
            "line1": {
              "type": "string",
              "description": "Individual's first line of address."
            },
            "line2": {
              "type": "string",
              "description": "Individual's second line of address."
            },
            "postcode": {
              "type": "string",
              "description": "Individual's postcode."
            }
          },
          "required": [
            "line1",
            "line2",
            "postcode"
          ]
        }
      },
      "required": [
        "firstName",
        "lastName",
        "dateOfBirth",
        "address"
      ]
    },
    "saUtr": {
      "type": "string",
      "description": "Self Assessment UTR."
    },
    "nino": {
      "type": "string",
      "description": "National Insurance number."
    },
    "mtdItId": {
      "type": "string",
      "description": "Making Tax Digital Income Tax ID."
    },
    "eoriNumber": {
      "type": "string",
      "description": "Economic Operator Registration and Identification (EORI) number."
    },
    "vrn": {
      "type": "string",
      "description": "VAT Reference Number."
    },
    "vatRegistrationDate": {
      "type": "string",
      "format": "date",
      "description": "Date of registration for VAT."
    },
    "capitalGainsTaxOnUKPropertyReference": {
      "type": "string",
      "description": "Capital Gains Tax on UK Property reference."
    },
    "plasticPackagingTaxRegistrationNumber": {
      "type": "string",
      "description": "Plastic Packaging Tax registration number."
    }
  },
  "required": [
    "userId",
    "password",
    "userFullName",
    "emailAddress",
    "individualDetails"
  ]
}

=== hmrc/api-platform-test-user/resources/public/api/conf/1.0/examples/create-individual-response.json
{
  "userId":"945350439195",
  "password":"bLohysg8utsa",
  "userFullName": "Ida Newton",
  "emailAddress": "ida.newton@example.com",
  "individualDetails": {
    "firstName": "Ida",
    "lastName": "Newton",
    "dateOfBirth": "1960-06-01",
    "address": {
      "line1": "45 Springfield Rise",
      "line2": "Glasgow",
      "postcode": "TS1 1PA"
    }
  },
  "saUtr":"1000057161",
  "nino":"PE938808A",
  "mtdItId":"XJIT00000328268",
  "vrn":"666119668",
  "vatRegistrationDate":"2001-11-02",
  "eoriNumber":"GB123456789012",
  "capitalGainsTaxOnUKPropertyReference":"XACGTP123456789",
  "plasticPackagingTaxRegistrationNumber":"XAPPT0001234567"
}
