openapi: 3.0.3
info:
  title: Create Test User
  contact: {}
  version: '1.0'
servers:
- url: https://api.service.hmrc.gov.uk/
  variables: {}
paths:
  /create-test-user/individuals:
    post:
      tags:
      - create-test-user
      summary: Create a test user which is an individual
      description: This resource creates and returns a test user which is an individual. The caller can specify the required service enrolments in the request body. If no request body is supplied, the test user is created with no service enrolments.
      operationId: Createatestuserwhichisanindividual
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/CreateTestUserIndividualsrequest'
              - example:
                  serviceNames:
                  - national-insurance
                  - self-assessment
                  - mtd-income-tax
                  - customs-services
                  - goods-vehicle-movements
                  - mtd-vat
                  - common-transit-convention-traders
                  - common-transit-convention-traders-legacy
                  eoriNumber: GB123456789012
            example:
              serviceNames:
              - national-insurance
              - self-assessment
              - mtd-income-tax
              - customs-services
              - goods-vehicle-movements
              - mtd-vat
              - common-transit-convention-traders
              - common-transit-convention-traders-legacy
              eoriNumber: GB123456789012
        required: true
      responses:
        '201':
          description: The individual test user resource has been created.
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/CreateTestUserIndividualsresponse'
                - example:
                    userId: '945350439195'
                    password: bLohysg8utsa
                    userFullName: Ida Newton
                    emailAddress: ida.newton@example.com
                    individualDetails:
                      firstName: Ida
                      lastName: Newton
                      dateOfBirth: 1960-06-01
                      address:
                        line1: 45 Springfield Rise
                        line2: Glasgow
                        postcode: TS1 1PA
                    saUtr: '1000057161'
                    nino: PE938808A
                    mtdItId: XJIT00000328268
                    vrn: '666119668'
                    vatRegistrationDate: 2001-11-02
                    eoriNumber: GB123456789012
              example:
                userId: '945350439195'
                password: bLohysg8utsa
                userFullName: Ida Newton
                emailAddress: ida.newton@example.com
                individualDetails:
                  firstName: Ida
                  lastName: Newton
                  dateOfBirth: 1960-06-01
                  address:
                    line1: 45 Springfield Rise
                    line2: Glasgow
                    postcode: TS1 1PA
                saUtr: '1000057161'
                nino: PE938808A
                mtdItId: XJIT00000328268
                vrn: '666119668'
                vatRegistrationDate: 2001-11-02
                eoriNumber: GB123456789012
      security:
      - applicationRestricted: []
      deprecated: false
  /create-test-user/organisations:
    post:
      tags:
      - create-test-user
      summary: Create a test user which is an organisation
      description: This resource creates and returns a test user which is an organisation. The caller can specify the required service enrolments in the request body. If no request body is supplied, the test user is created with no service enrolments.
      operationId: Createatestuserwhichisanorganisation
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/CreateTestUserOrganisationsrequest'
              - example:
                  serviceNames:
                  - corporation-tax
                  - paye-for-employers
                  - submit-vat-returns
                  - national-insurance
                  - self-assessment
                  - mtd-income-tax
                  - mtd-vat
                  - lisa
                  - secure-electronic-transfer
                  - relief-at-source
                  - customs-services
                  - goods-vehicle-movements
                  - safety-and-security
                  - common-transit-convention-traders
                  - common-transit-convention-traders-legacy
                  eoriNumber: GB123456789012
                  taxPayerType: Individual
            example:
              serviceNames:
              - corporation-tax
              - paye-for-employers
              - submit-vat-returns
              - national-insurance
              - self-assessment
              - mtd-income-tax
              - mtd-vat
              - lisa
              - secure-electronic-transfer
              - relief-at-source
              - customs-services
              - goods-vehicle-movements
              - safety-and-security
              - common-transit-convention-traders
              - common-transit-convention-traders-legacy
              eoriNumber: GB123456789012
              taxPayerType: Individual
        required: true
      responses:
        '201':
          description: The organisation test user resource has been created.
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/CreateTestUserOrganisationsresponse'
                - example:
                    userId: '085603622877'
                    password: nyezgdfrlsmc
                    userFullName: Ida Newton
                    emailAddress: ida.newton@example.com
                    organisationDetails:
                      name: Company ABF123
                      address:
                        line1: 1 Abbey Road
                        line2: Aberdeen
                        postcode: TS1 1PA
                    individualDetails:
                      firstName: Ida
                      lastName: Newton
                      dateOfBirth: 1960-06-01
                      address:
                        line1: 45 Springfield Rise
                        line2: Glasgow
                        postcode: TS1 1PA
                    saUtr: '8000083480'
                    nino: XM110477D
                    empRef: 538/EMKXYNSVTH
                    ctUtr: '4000082459'
                    vrn: '666119668'
                    vatRegistrationDate: 2001-11-02
                    mtdItId: XJIT00000328268
                    lisaManagerReferenceNumber: Z123456
                    secureElectronicTransferReferenceNumber: '123456789012'
                    pensionSchemeAdministratorIdentifier: A1234567
                    eoriNumber: GB123456789012
                    crn: '12345678'
                    taxPayerType: Individual
              example:
                userId: '085603622877'
                password: nyezgdfrlsmc
                userFullName: Ida Newton
                emailAddress: ida.newton@example.com
                organisationDetails:
                  name: Company ABF123
                  address:
                    line1: 1 Abbey Road
                    line2: Aberdeen
                    postcode: TS1 1PA
                individualDetails:
                  firstName: Ida
                  lastName: Newton
                  dateOfBirth: 1960-06-01
                  address:
                    line1: 45 Springfield Rise
                    line2: Glasgow
                    postcode: TS1 1PA
                saUtr: '8000083480'
                nino: XM110477D
                empRef: 538/EMKXYNSVTH
                ctUtr: '4000082459'
                vrn: '666119668'
                vatRegistrationDate: 2001-11-02
                mtdItId: XJIT00000328268
                lisaManagerReferenceNumber: Z123456
                secureElectronicTransferReferenceNumber: '123456789012'
                pensionSchemeAdministratorIdentifier: A1234567
                eoriNumber: GB123456789012
                crn: '12345678'
                taxPayerType: Individual
      security:
      - applicationRestricted: []
      deprecated: false
  /create-test-user/agents:
    post:
      tags:
      - create-test-user
      summary: Create a test user which is an agent
      description: This resource creates and returns a test user which is an agent. The caller can specify the required service enrolments in the request body. If no request body is supplied, the test user is created with no service enrolments.
      operationId: Createatestuserwhichisanagent
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/CreateTestUserAgentsrequest'
              - example:
                  serviceNames:
                  - agent-services
            example:
              serviceNames:
              - agent-services
        required: true
      responses:
        '201':
          description: The agent test user resource has been created.
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/CreateTestUserAgentsresponse'
                - example:
                    userId: '945350439195'
                    password: 'bLohysg8utsa '
                    userFullName: Ida Newton
                    emailAddress: ida.newton@example.com
                    agentServicesAccountNumber: NARN0396245
              example:
                userId: '945350439195'
                password: 'bLohysg8utsa '
                userFullName: Ida Newton
                emailAddress: ida.newton@example.com
                agentServicesAccountNumber: NARN0396245
      security:
      - applicationRestricted: []
      deprecated: false
  /create-test-user/services:
    get:
      tags:
      - create-test-user
      summary: Get available services
      description: This resource provides a list of all the available services together with which test user types can enrol to each.
      operationId: Getavailableservices
      parameters: []
      responses:
        '200':
          description: The services available for enrolment
          headers: {}
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CreateTestUserServicesresponse'
                description: ''
                example:
                - key: service1
                  name: Service 1
                  allowedUserTypes:
                  - INDIVIDUAL
                  - ORGANISATION
                - key: service2
                  name: Service 2
                  allowedUserTypes:
                  - AGENT
              example:
              - key: service1
                name: Service 1
                allowedUserTypes:
                - INDIVIDUAL
                - ORGANISATION
              - key: service2
                name: Service 2
                allowedUserTypes:
                - AGENT
      security:
      - applicationRestricted: []
      deprecated: false
components:
  securitySchemes:
    applicationRestricted:
      type: oauth2
      description: |
        HMRC supports OAuth 2.0 for authenticating application restricted API requests using an OAuth 2.0 Bearer Token in the AUTHORIZATION header.
        See https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/application-restricted-endpoints for details.
      flows:
        clientCredentials:
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          scopes: {}
  schemas:
    errorResponse:
      title: errorResponse
      required:
      - code
      type: object
      properties:
        code:
          type: string
    IndividualAddress:
      title: Address
      required:
      - line1
      - line2
      - postcode
      type: object
      properties:
        line1:
          type: string
          description: Individual's first line of address.
        line2:
          type: string
          description: Individual's second line of address.
        postcode:
          type: string
          description: Individual's postcode.
    OrganisationAddress:
      title: Address
      required:
      - line1
      - line2
      - postcode
      type: object
      properties:
        line1:
          type: string
          description: Organisation's first line of address.
        line2:
          type: string
          description: Organisation's second line of address.
        postcode:
          type: string
          description: Organisation's postcode.
    CreateTestUserAgentsrequest:
      title: CreateTestUserAgentsrequest
      required:
      - serviceNames
      type: object
      properties:
        serviceNames:
          minItems: 0
          uniqueItems: true
          type: array
          items:
            oneOf:
            - $ref: '#/components/schemas/AgentServices'
          description: A list of services that the user should be enrolled for. To create a test user with no services, leave the list empty.
      description: Create Agent Request
    CreateTestUserAgentsresponse:
      title: CreateTestUserAgentsresponse
      required:
      - userId
      - password
      - userFullName
      - emailAddress
      type: object
      properties:
        userId:
          type: string
          description: Government Gateway ID.
        password:
          type: string
          description: Government Gateway password.
        userFullName:
          type: string
          description: Government Gateway user's full name.
        emailAddress:
          type: string
          description: Government Gateway user's email address.
        agentServicesAccountNumber:
          type: string
          description: Agent services account reference number.
      description: Create Agent Response
    CreateTestUserIndividualsrequest:
      title: CreateTestUserIndividualsrequest
      required:
      - serviceNames
      type: object
      properties:
        serviceNames:
          minItems: 0
          uniqueItems: true
          type: array
          items:
            oneOf:
            - $ref: '#/components/schemas/NationalInsurance'
            - $ref: '#/components/schemas/SelfAssessment'
            - $ref: '#/components/schemas/MtdIncomeTax'
            - $ref: '#/components/schemas/CustomsServices'
            - $ref: '#/components/schemas/GoodsVehicleMovements'
            - $ref: '#/components/schemas/MtdVat'
            - $ref: '#/components/schemas/CommonTransitConventionTraders'
            - $ref: '#/components/schemas/CommonTransitConventionTradersLegacy'
          description: A list of services that the user should be enrolled for. To create a test user with no services, leave the list empty.
        eoriNumber:
          maxLength: 17
          minLength: 14
          pattern: ^(GB|XI)[0-9]{12,15}$
          type: string
          description: Economic Operator Registration and Identification (EORI) number.
        nino:
          type: string
          description: National Insurance number. Must be enrolled with 'national-insurance' or 'mtd-income-tax' services for this to be used.
      description: Create Individual Request
    CreateTestUserIndividualsresponse:
      title: CreateTestUserIndividualsresponse
      required:
      - userId
      - password
      - userFullName
      - emailAddress
      - individualDetails
      type: object
      properties:
        userId:
          type: string
          description: Government Gateway ID.
        password:
          type: string
          description: Government Gateway password.
        userFullName:
          type: string
          description: Government Gateway user's full name.
        emailAddress:
          type: string
          description: Government Gateway user's email address.
        individualDetails:
          $ref: '#/components/schemas/IndividualDetails'
        saUtr:
          type: string
          description: Self Assessment UTR.
        nino:
          type: string
          description: National Insurance number.
        mtdItId:
          type: string
          description: Making Tax Digital Income Tax ID.
        eoriNumber:
          type: string
          description: Economic Operator Registration and Identification (EORI) number.
        vrn:
          type: string
          description: VAT Reference Number.
        vatRegistrationDate:
          type: string
          description: Date of registration for VAT.
          format: date
      description: Create Individual Response
    CreateTestUserOrganisationsrequest:
      title: CreateTestUserOrganisationsrequest
      required:
      - serviceNames
      type: object
      properties:
        serviceNames:
          minItems: 0
          uniqueItems: true
          type: array
          items:
            oneOf:
            - $ref: '#/components/schemas/CorporationTax'
            - $ref: '#/components/schemas/PayeForEmployers'
            - $ref: '#/components/schemas/SubmitVatReturns'
            - $ref: '#/components/schemas/NationalInsurance'
            - $ref: '#/components/schemas/SelfAssessment'
            - $ref: '#/components/schemas/MtdIncomeTax'
            - $ref: '#/components/schemas/MtdVat'
            - $ref: '#/components/schemas/Lisa'
            - $ref: '#/components/schemas/SecureElectronicTransfer'
            - $ref: '#/components/schemas/ReliefAtSource'
            - $ref: '#/components/schemas/CustomsServices'
            - $ref: '#/components/schemas/GoodsVehicleMovements'
            - $ref: '#/components/schemas/SafetyAndSecurity'
            - $ref: '#/components/schemas/CommonTransitConventionTraders'
            - $ref: '#/components/schemas/CommonTransitConventionTradersLegacy'
          description: A list of services that the user should be enrolled for. To create a test user with no services, leave the list empty.
        eoriNumber:
          maxLength: 17
          minLength: 14
          pattern: ^(GB|XI)[0-9]{12,15}$
          type: string
          description: Economic Operator Registration and Identification (EORI) number.
        nino:
          type: string
          description: National Insurance number. Must be enrolled with 'national-insurance' or 'mtd-income-tax' services for this to be used.
        taxPayerType:
          type: string
          description: Type of Self Assessment taxpayer One of 'Individual' or 'Partnership'
      description: Create Organisation Request
    CreateTestUserOrganisationsresponse:
      title: CreateTestUserOrganisationsresponse
      required:
      - userId
      - password
      - userFullName
      - emailAddress
      - organisationDetails
      type: object
      properties:
        userId:
          type: string
          description: Government Gateway ID.
        password:
          type: string
          description: Government Gateway password.
        userFullName:
          type: string
          description: Government Gateway user's full name.
        emailAddress:
          type: string
          description: Government Gateway user's email address.
        organisationDetails:
          $ref: '#/components/schemas/OrganisationDetails'
        individualDetails:
          $ref: '#/components/schemas/IndividualDetails'
        saUtr:
          type: string
          description: Self Assessment UTR.
        nino:
          type: string
          description: National Insurance number.
        mtdItId:
          type: string
          description: Making Tax Digital Income Tax ID.
        empRef:
          type: string
          description: Employer Reference.
        ctUtr:
          type: string
          description: Corporation Tax UTR.
        vrn:
          type: string
          description: VAT Reference Number.
        vatRegistrationDate:
          type: string
          description: Date of registration for VAT.
          format: date
        lisaManagerReferenceNumber:
          type: string
          description: LISA Manager Reference Number, in either 4-digit format (Znnnn) or 6-digit format (Znnnnnn).
        secureElectronicTransferReferenceNumber:
          type: string
          description: Secure Electronic Transfer reference number.
        pensionSchemeAdministratorIdentifier:
          type: string
          description: Pension Scheme Administrator Identifier.
        eoriNumber:
          type: string
          description: Economic Operator Registration and Identification (EORI) number.
        crn:
          type: string
          description: Company Reference Number
        taxPayerType:
          type: string
          description: Type of Self Assessment taxpayer One of 'Individual' or 'Partnership'
      description: Create Organisation Response
    CreateTestUserServicesresponse:
      title: CreateTestUserServicesresponse
      type: object
      properties:
        key:
          type: string
          description: The key of the service
        name:
          type: string
          description: The human readable name of the service
        allowedUserTypes:
          type: array
          items:
            type: string
          description: The user types which may enrol to the service
    IndividualDetails:
      title: IndividualDetails
      required:
      - firstName
      - lastName
      - dateOfBirth
      - address
      type: object
      properties:
        firstName:
          type: string
          description: Individual's first name.
        lastName:
          type: string
          description: Individual's last name.
        dateOfBirth:
          type: string
          description: Individual's date of birth.
          format: date
        address:
          $ref: '#/components/schemas/IndividualAddress'
    OrganisationDetails:
      title: OrganisationDetails
      required:
      - name
      - address
      type: object
      properties:
        name:
          type: string
          description: Organisation name.
        address:
          $ref: '#/components/schemas/OrganisationAddress'
    NationalInsurance:
      title: national-insurance
      enum:
      - national-insurance
      type: string
      description: Generates a National Insurance number and enrols the user for National Insurance.
    SelfAssessment:
      title: self-assessment
      enum:
      - self-assessment
      type: string
      description: Generates a Self Assessment UTR and enrols the user for Self Assessment.
    MtdIncomeTax:
      title: mtd-income-tax
      enum:
      - mtd-income-tax
      type: string
      description: Generates a National Insurance number and a Making Tax Digital Income Tax ID and enrols the user for Making Tax Digital Income Tax.
    CustomsServices:
      title: customs-services
      enum:
      - customs-services
      type: string
      description: Generates an EORI number and enrols the user for Customs Services.
    GoodsVehicleMovements:
      title: goods-vehicle-movements
      enum:
      - goods-vehicle-movements
      type: string
      description: Generates an EORI number and enrols the user for Goods Vehicle Movements.
    MtdVat:
      title: mtd-vat
      enum:
      - mtd-vat
      type: string
      description: Generates a VAT Registration Number and a date of registration for VAT and enrols the user for Making Tax Digital VAT.
    CommonTransitConventionTraders:
      title: common-transit-convention-traders
      enum:
      - common-transit-convention-traders
      type: string
      description: Generates an EORI number and enrols the user for Common Transit Convention Traders.
    CommonTransitConventionTradersLegacy:
      title: common-transit-convention-traders-legacy
      enum:
      - common-transit-convention-traders-legacy
      type: string
      description: Generates an EORI number and enrols the user for legacy Common Transit Convention Traders.
    CorporationTax:
      title: corporation-tax
      enum:
      - corporation-tax
      type: string
      description: Generates a Corporation Tax Unique Taxpayer Reference (CTUTR), a Company Registration Number (CRN) and enrols the user for Corporation Tax.
    AgentServices:
      title: agent-services
      enum:
      - agent-services
      type: string
      description: Generates an agent services account reference number and enrols the user for agent services.
    PayeForEmployers:
      title: paye-for-employers
      enum:
      - paye-for-employers
      type: string
      description: Generates an Employer Reference and enrols the user for PAYE for Employers.
    SubmitVatReturns:
      title: submit-vat-returns
      enum:
      - submit-vat-returns
      type: string
      description: Generates a VAT Registration Number and enrols the user for Submit VAT Returns.
    Lisa:
      title: lisa
      enum:
      - lisa
      type: string
      description: Generates a LISA Manager Reference Number and enrols the user for Lifetime ISA.
    SecureElectronicTransfer:
      title: secure-electronic-transfer
      enum:
      - secure-electronic-transfer
      type: string
      description: Generates a Secure Electronic Transfer Reference Number and enrols the user for HMRC Secure Electronic Transfer.
    ReliefAtSource:
      title: relief-at-source
      enum:
      - relief-at-source
      type: string
      description: Generates a Pension Scheme Administrator Identifier and enrols the user for Relief at Source.
    SafetyAndSecurity:
      title: safety-and-security
      enum:
      - safety-and-security
      type: string
      description: Generates an EORI number and enrols the user for Safety and Security.
tags:
- name: create-test-user
  description: ''
